apiVersion: v1
kind: Service
metadata:
  name: bigtable-autoscaler
spec:
  selector:
    app: bigtable-autoscaler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
